//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoViernes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Productos
    {
        public int IdProducto { get; set; }
        public string Nombre { get; set; }
        public long Precio { get; set; }
        public int Cantidad { get; set; }
        public string Descripcion { get; set; }
        public int IdProvedor { get; set; }
    
        public virtual Tb_Provedores Tb_Provedores { get; set; }
    }
}
